# Generated by Django 2.1.3 on 2018-11-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salestable',
            old_name='salesID',
            new_name='worker',
        ),
        migrations.RemoveField(
            model_name='salestable',
            name='staffID',
        ),
        migrations.RemoveField(
            model_name='salestable',
            name='totalmoney',
        ),
    ]
