# Generated by Django 2.1.3 on 2018-11-16 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MMS', '0002_auto_20181116_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importtable',
            old_name='woeker',
            new_name='worker',
        ),
    ]
