# Generated by Django 2.1.3 on 2018-11-17 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MMS', '0004_auto_20181117_0222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stortable',
            old_name='goodName',
            new_name='goods',
        ),
    ]
